### ISSUE TITLE
Active pane in copy-mode scrolls without events forwarded directly to it

### ISSUE THREAD

**Issue by cHoco** [tmux/tmux#160]
I use the following binding for scrolling:
``` tmux
# Check if copy-mode or any mouse flags, then send mouse events
# or check if we're in alternate screen end send navigation keys (up, down)
bind -n WheelUpPane if-shell -Ft= '#{?pane_in_mode,1,#{mouse_any_flag}}' \
        'send -Mt=' 'if-shell -Ft= "#{alternate_on}" \
        "send -t= Up" "copy-mode -et="'
bind -n WheelDownPane if-shell -Ft = '#{?pane_in_mode,1,#{mouse_any_flag}}' \
        'send -Mt=' 'if-shell -Ft= "#{alternate_on}" \
        "send -t= Down" "send -Mt="'
```

And I happily school whatever I like. 

But if a have two panes, pane A active and in copy-mode and pane B in vim for example (NOT ACTIVE), and I scroll over pane B both pane A and pane B scroll.
This doesn't happen if pane B is the active one, or if neither pane A or B are in copy-mode

**Comment by nicm** [comment]
Can't reproduce, are you sure it happens with just the config you have included? Please try with a new server with just those two lines and "set -g mouse on".

**Comment by cHoco** [comment]
Yes, I can reproduce even with just the default bindings. Different terminal emulator behave differently, for example can reproduce constantly with Terminal.app on OS X, after plenty of scrolling with iTerm and almost never with mlterm

**Comment by nicm** [comment]
Please reproduce with tmux with minimal config and two panes and run with -vvv and show me the tmux-server-*.log file.

**Comment by cHoco** [comment]
Here's the minimal cons that I used to reproduce
``` tmux
set -g mouse on
bind-key -T root WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M -t =" "if -Ft= '#{pane_in_mode}' 'send-keys -M -t =' 'copy-mode -e -t ='"
```
It's the standard mapping, just needed to add `-t =` since I want to send the mouse event to the panel on which I'm hovering

Here's the server log file: https://gist.github.com/e9f26d75d39e72209842
I start neovim in a panel, then split the window, enter copy-mode, scroll over vim panel.

**Comment by nicm** [comment]
And you only ever scrolled over the righthand pane, and did not move
your mouse at all while you were scrolling?

**Comment by cHoco** [comment]
First I scrolled in the right pane (the active one) to enter copy-mode, then scrolled in the left one. At this point when I start scrolling in the left one (the one with vim) the right pane also scrolls (and quits copy-mode because scrolled over the end; when out of copy mode the right panel doesn't scroll together with the left one anymore)

**Comment by nicm** [comment]
The log has you scrolling in right pane, left pane, and then right pane
again, there is no evidence in th log of tmux scrolling the right pane
when it gets a wheel event in the left pane. Are you using a mouse or a
touchpad?

**Comment by cHoco** [comment]
I'm using a touchpad in that session, but I can reproduce it with a mouse and a scroll wheel.
Here's a video that maybe better shows what I do during the logging: https://www.youtube.com/watch?v=JI0QOjVYOEg
and here's the corresponding log: https://gist.github.com/b0be385bf48469bd0312
I'm using a mouse with scroll wheel in this case.

**Comment by nicm** [comment]
Weird. I think send-keys might be getting the wrong pane, but it is odd it sends to both. Can you apply this change please then do the same and show me the new log http://pastebin.ca/raw/3219734

**Comment by cHoco** [comment]
There you go: https://gist.github.com/7af2abb2090b82d570e6
I did exactly the same process as in the video.

**Comment by nicm** [comment]
Please add this too and do the same:

diff --git a/server-client.c b/server-client.c
index 08bf502..57f0de4 100644
--- a/server-client.c
+++ b/server-client.c
@@ -368,6 +368,8 @@ server_client_check_mouse(struct client *c)
 			wp = window_get_active_at(s->curw->window, x, y);
 			if (wp != NULL)
 				where = PANE;
+			log_debug("mouse at %u,%u is on pane %%%u", x, y,
+			    wp->id);
 		}
 		if (where == NOWHERE)
 			return (KEYC_NONE);

**Comment by cHoco** [comment]
Done: https://gist.github.com/35a0fd3f310f9a8924a5
Thank you again for taking time to review this.

**Comment by nicm** [comment]
Gah, it still looks fine, can you try with this as well to see if copy
mode is actually getting any keys?

diff --git a/window-copy.c b/window-copy.c
index f81a2a1..8d634ac 100644
--- a/window-copy.c
+++ b/window-copy.c
@@ -378,6 +378,8 @@ window_copy_key(struct window_pane *wp, struct client *c, struct session *sess,
 	enum mode_key_cmd		 cmd;
 	const char			*arg, *ss;
 
+	log_debug("XXX %%%u %#x %s", wp->id, key, key_string_lookup_key (key));
+
 	np = 1;
 	if (data->numprefix > 0)
 		np = data->numprefix;

**Comment by cHoco** [comment]
Here: https://gist.github.com/17cfbbb5e40bffa85a62

**Comment by nicm** [comment]
Hmm are you using 2.1? Can you either try tmux master from git or try
"set -g assume-paste-time 0" and see if either fixes it?

I think the mouse wheel is getting to the wrong pane because it is
hitting the assume-paste check which just passes it through to the
active pane, not the pane where the mouse is. This has been fixed after
2.1.

**Comment by cHoco** [comment]
No, I'm already using tmux master from git. Setting  that option
doesn't fix the issue :(

**Comment by nicm** [comment]
Ok try this then please and again show me the log:

diff --git a/server-client.c b/server-client.c
index 57f0de4..380166d 100644
--- a/server-client.c
+++ b/server-client.c
@@ -592,6 +592,7 @@ server_client_handle_key(struct client *c, int key)
 		m->key = key;
 
 		if (!options_get_number(&s->options, "mouse")) {
+			log_debug("AAA mouse off %%%u for %#x", wp->id, key);
 			window_pane_key(wp, c, s, key, m);
 			return;
 		}
@@ -600,6 +601,7 @@ server_client_handle_key(struct client *c, int key)
 
 	/* Treat everything as a regular key when pasting is detected. */
 	if (!KEYC_IS_MOUSE(key) && server_client_assume_paste(s)) {
+		log_debug("BBB assume paste %%%u for %#x", wp->id, key);
 		if (!(c->flags & CLIENT_READONLY))
 			window_pane_key(wp, c, s, key, m);
 		return;
@@ -610,6 +612,7 @@ retry:
 	bd_find.key = key;
 	bd = RB_FIND(key_bindings, &c->keytable->key_bindings, &bd_find);
 	if (bd != NULL) {
+		log_debug("CCC key binding %%%u for %#x", wp->id, key);
 		/*
 		 * Key was matched in this table. If currently repeating but a
 		 * non-repeating binding was found, stop repeating and try
@@ -679,8 +682,10 @@ retry:
 	    key == options_get_number(&s->options, "prefix2")) {
 		server_client_key_table(c, "prefix");
 		server_status_client(c);
-	} else if (!(c->flags & CLIENT_READONLY))
+	} else if (!(c->flags & CLIENT_READONLY)) {
+		log_debug("DDD key pressed %%%u for %#x", wp->id, key);
 		window_pane_key(wp, c, s, key, m);
+	}
 }
 
 /* Client functions that need to happen every loop. */

**Comment by cHoco** [comment]
Here's the new log: https://gist.github.com/6a951726482c797917ad

**Comment by nicm** [comment]
Ok, I can't see where it is getting the wrong pane at all.

Can you clean out all the previous changes and try this instead?

diff --git a/cmd-send-keys.c b/cmd-send-keys.c
index b1f8d67..2f67f3e 100644
--- a/cmd-send-keys.c
+++ b/cmd-send-keys.c
@@ -57,6 +57,7 @@ cmd_send_keys_exec(struct cmd *self, struct cmd_q *cmdq)
 
 	if (args_has(args, 'M')) {
 		wp = cmd_mouse_pane(m, &s, NULL);
+		log_debug("XXX %s %%%u", __func__, wp->id);
 		if (wp == NULL) {
 			cmdq_error(cmdq, "no mouse target");
 			return (CMD_RETURN_ERROR);
diff --git a/server-client.c b/server-client.c
index 57f0de4..e886b75 100644
--- a/server-client.c
+++ b/server-client.c
@@ -551,6 +551,7 @@ server_client_handle_key(struct client *c, int key)
 		return;
 	w = s->curw->window;
 	wp = w->active;
+	log_debug("XXX %s %%%u", __func__, wp->id);
 
 	/* Update the activity timer. */
 	if (gettimeofday(&c->activity_time, NULL) != 0)
diff --git a/window-copy.c b/window-copy.c
index f81a2a1..8d634ac 100644
--- a/window-copy.c
+++ b/window-copy.c
@@ -378,6 +378,8 @@ window_copy_key(struct window_pane *wp, struct client *c, struct session *sess,
 	enum mode_key_cmd		 cmd;
 	const char			*arg, *ss;
 
+	log_debug("XXX %%%u %#x %s", wp->id, key, key_string_lookup_key (key));
+
 	np = 1;
 	if (data->numprefix > 0)
 		np = data->numprefix;

**Comment by cHoco** [comment]
Applied only the newest patch: https://gist.github.com/d42dff6e4c60a3b2b1b8

**Comment by nicm** [comment]
Try this please http://pastebin.ca/raw/3220433. Because WheelDown1Pane has no binding, it is being sent to the active pane not to the mouse pane.

**Comment by cHoco** [comment]
This patch fixes it for me!

**Comment by nicm** [comment]
Great, applied, thanks.

**Comment by cHoco** [comment]
Hey thank you so much for all the time you dedicated to my issue. Do you guys accept donations? I would gladly pay you a drink for all the effort you spend on this amazing project :)

**Comment by nicm** [comment]
No it's ok, thanks
