### ISSUE TITLE
open terminal failed: can't find terminfo database on MacOS iterm2

### ISSUE THREAD

**Issue by MrZhang123** [tmux/tmux#1672]
I install tmux with Homebrew, I run `tmux` in iterm2, get error:

```
open terminal failed: can't find terminfo database
```

### platform

MacOS 10.14.4

### log

run `$ uname -sp && tmux -V && echo $TERM`

```
Darwin i386
tmux 2.8
xterm-256color
```
run `$ tmux -vv -Ltest -f/dev/null new` get tmux log:

[tmux-server log](https://gist.github.com/MrZhang123/5b13496886ff6a76e254e122fef66399)

[tmux-client log](https://gist.github.com/MrZhang123/85369171c96e7f0e24036d8314b5f0f7)

**Comment by nicm** [comment]
This sounds like a build problem, I suggest you ask the package maintainer.

**Comment by MrZhang123** [comment]
@nicm Thanks for you reply, I fixed it, because tmux dependencies ncurses broken, I reinstall it , and the problem fixed.

**Comment by nicm** [comment]
Great stuff.

**Comment by paymog** [comment]
@MrZhang123 what version of ncurses are you on? I just ran into this problem myself. How did you diagnose the problem with ncurses?

**Comment by xanderflood** [comment]
I also just started having this issue - `brew reinstall tmux` and `brew reinstall ncurses` didn't resolve it

**Comment by xanderflood** [comment]
Ah just found [this](https://github.com/tmux/tmux/issues/743) and `tmux kill-server` did work for me

**Comment by benw01** [comment]
For anyone finding this on google: I had a similar issue with tmux (not kitty related). When I detached from my running tmux session, I couldn't subsequently re-attach, with the same error message: `open terminal failed: can't find terminfo database`.

* MacOS Mojave (10.14.6)
* tmux 3.0a
* Terminal.app

Turns out homebrew had upgraded ncurses (from 6.1_1 to 6.2) from underneath my running tmux server process, and deleted the folder for the previous ncurses under `/usr/local/Cellar/ncurses`.

I restored ` /usr/local/Cellar/ncurses/6.1_1` from a backup, and was then able to `tmux att` again.
