### ISSUE TITLE
Tmux gets frozen with RHEL8

### ISSUE THREAD

**Issue by sksd509** [tmux/tmux#2380]
### Issue description
I am consistently seeing tmux getting frozen and then since I am in tmux mode nothing is working for me unless it unfreezes itself _(once I migrated from RHEL6 to RHEL8, with tmux 2.6 in place)._ 

- Please, note that I have tried `Ctrl + Q` and `sending a signal to running tmux server `and all, none of them works and tmux has to **_itself come out of that frozen mode_** and then I can resume my work.
- It is annoying given that the time to wait, can be like 3 to 4 mins and when in shared debugging sessions it just adds trouble for all!

### Required information

Please provide the following information:
* tmux version (`tmux -V`).
  - tmux.bin 2.6
* Platform (`uname -sp`).
  - Linux x86_64
* $TERM inside and outside of tmux (`echo $TERM`).
  - xterm-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`).
  - NA

In the end, can someone please give me a `viable solution` to unfreeze it?
Or if not, at least suggest me the `recommended version` of tmux to be used with RHEL8?

**Comment by nicm** [comment]
Does this still happen with master or 3.2-rc?

**Comment by sksd509** [comment]
@nicm No Actually this is not my system, but my company's and hence I need to be sure before trying to tell them to update the tmux version. Cause many people would be sticking to it!
Do tmux versions have any `associativity` with RHEL version?

**Comment by nicm** [comment]
tmux 2.6 is almost 3 years old, there have been a lot of changes since, I don't have time to look at problems that may already be fixed in a newer version. There is no connection between tmux and RHEL. You should be able to build tmux from source yourself.

**Comment by sksd509** [comment]
@nicm Thanks

I have pointed out the similar issue to the IT support here, things would be moving fast if someone can please say like what is the `ideal tmux (stable) version` to be used across OS **(as of today)**

**Comment by nicm** [comment]
The lastest tmux is 3.1b or you can try 3.2-rc.

**Comment by sksd509** [comment]
Thanks, @nicm will try some latest version and let you know...
Closing this discussion until then!

**Comment by sksd509** [comment]
Hi @nicm , I have migrated to tmux 3.1b(on the remote server)
```
[0s][~]> tmux -V
tmux.bin 3.1b
```

The issue still remains, please help me fix this(am I on the wrong version or on wrong tmux configs?)
My ~/.tmux.conf : 
```
#for having color support                                                                                                                                                                
set -g default-terminal "screen-256color"                                          
#for having scrollback limit set to a limit as u desire                            
set -g history-limit 10000000                                                      
                                                                                   
#tmux2.1 and above mouse support                                                   
set-option -g mouse on                                                             
# make scrolling with wheels work                                                  
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'select-pane -t=; copy-mode -e; send-keys -M'"
bind -n WheelDownPane select-pane -t= \; send-keys -M
``` 

My setup details can be seen [here](https://gitlab.com/gnachman/iterm2/-/issues/9111#note_408090502
)!

**Comment by nicm** [comment]
That is an extremely large history-limit, are you sure tmux is not being swapped out? How much memory is it using when it freezes?

How do you reproduce? Does it just happen randomly while you are using it? Or only on attach or what?

**Comment by sksd509** [comment]
Sorry, for late comment here. Sincere apologies, please see my _response_ : 
  - Sure @nicm  I will try to collect these outputs whenever next it gets stuck. There is no repro step but mostly it happens randomly and then all the tmux sessions on the remote freezes for like `3 to 7 mins.`
  - Please note here, that in this case, `tmux freezes ` is confirmed cause if I connect to my remote machine via **SSH** or **MOSH** the tmux **remains frozen** that time.

  - Also, What would be the **ideal** history limit, cause I am just using some max limit to not loose out build logs.

**Comment by nicm** [comment]
How much memory is your tmux using after it freezes?

**Comment by sksd509** [comment]
> How much memory is your tmux using after it freezes?

Sure, let me get it as soon as it next enters into the same state! thanks
