### ISSUE TITLE
command-alias expansion no longer works as expected when parameters are supplied.

### ISSUE THREAD

**Issue by systemmonkey42** [tmux/tmux#2842]
### Issue description

* tmux version (`tmux -V`).
  tmux next-3.3
* Platform (`uname -sp`) 
   Linux (Ubun
* $TERM inside and outside of tmux (`echo $TERM`).
  xterm-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`).
   available on request.

A number of my command-aliases have stopped working with the latest build and I'm not sure how to fix them.

I have (among others)
```
set-option -s command-alias[102] "csplit-window=split-window -c \"#{pane_current_path}\""
```
... later in the file
```
bind-key -T prefix       |                               csplit-window -h
```

With a previous build (Any before commit 84955e3 ) I woud get

```
$ tmux-3.2 list-key -P prefix '|'
bind-key -T prefix | split-window -h -c "#{pane_current_path}"
```
This works correctly to vertically split a window and open a new pane in the same directory.

As of commit 84955e3

Using the list-keys command I see:
```
$ tmux list-key -P prefix '|'
bind-key -T prefix | split-window -c -h "#{pane_current_path}"
```
This does not work, because the "-h" is now inserted between the -c and its argument.

Any suggestions?

Thanks

**Comment by nicm** [comment]
This is a bug, will take a look when I get home.

**Comment by nicm** [comment]
This is the fix, I got the argument it should insert after wrong:
~~~~
--- cmd-parse.y 21 Aug 2021 20:46:43 -0000      1.41
+++ cmd-parse.y 22 Aug 2021 12:59:07 -0000
@@ -772,7 +772,7 @@ cmd_parse_expand_alias(struct cmd_parse_
        TAILQ_REMOVE(&cmd->arguments, first, entry);
        cmd_parse_free_argument(first);

-       after = TAILQ_NEXT(TAILQ_FIRST(&last->arguments), entry);
+       after = TAILQ_FIRST(&last->arguments);
        TAILQ_FOREACH_SAFE(arg, &cmd->arguments, entry, arg1) {
                TAILQ_REMOVE(&cmd->arguments, arg, entry);
                if (after == NULL)
~~~~
I've applied this to OpenBSD now, it will be in GitHub later when it syncs.

Thanks!

**Comment by systemmonkey42** [comment]
Works beautifully.  Many thanks

**Comment by systemmonkey42** [comment]
Hi
The latest build seems to have reverted the issue.
Eg,
```
tmux csplit-window -h "top"
```
produces a "syntax error" message in the status line.

In the tmux logs you see
```
1631153928.057779 cmd_unpack_argv: argv[0]=csplit-window
1631153928.057781 cmd_unpack_argv: argv[1]=-h
1631153928.057783 cmd_unpack_argv: argv[2]=htop
1631153928.057787 cmd_parse_build_commands 0:0: csplit-window
1631153928.057789 cmd_parse_build_commands 0:1: -h
1631153928.057791 cmd_parse_build_commands 0:2: htop
1631153928.057795 cmd_parse_expand_alias: 0 alias csplit-window = split-window -c "#{pane_current_path}"
1631153928.057799 yylex_token: split-window
1631153928.057801 yylex_token: -c
1631153928.057804 yylex_token: #{pane_current_path}
1631153928.057808 cmd_parse_expand_alias 0:0: split-window
1631153928.057810 cmd_parse_expand_alias 0:1: -h
1631153928.057812 cmd_parse_expand_alias 0:2: htop
1631153928.057814 cmd_parse_expand_alias 0:3: -c
1631153928.057816 cmd_parse_expand_alias 0:4: #{pane_current_path}
1631153928.057818 cmd_parse_build_commands 0:0: split-window
1631153928.057820 cmd_parse_build_commands 0:1: -h
1631153928.057822 cmd_parse_build_commands 0:2: htop
1631153928.057824 cmd_parse_build_commands 0:3: -c
1631153928.057826 cmd_parse_build_commands 0:4: #{pane_current_path}
```
Which isn't the same behaviour it used to have.
```
1631154895.811834 cmd_unpack_argv: argv[0]=csplit-window
1631154895.811836 cmd_unpack_argv: argv[1]=-h
1631154895.811837 cmd_unpack_argv: argv[2]=htop
1631154895.811839 cmd_parse_from_arguments: argv[0]=csplit-window
1631154895.811840 cmd_parse_from_arguments: argv[1]=-h
1631154895.811841 cmd_parse_from_arguments: argv[2]=htop
1631154895.811843 cmd_parse_from_arguments: at 0: argv[0]=csplit-window
1631154895.811845 cmd_parse_from_arguments: at 0: argv[1]=-h
1631154895.811846 cmd_parse_from_arguments: at 0: argv[2]=htop
1631154895.811849 cmd_parse_build_commands: 0 csplit-window = split-window -c "#{pane_current_path}"
1631154895.811852 yylex_token: split-window
1631154895.811853 yylex_token: -c
1631154895.811855 yylex_token: #{pane_current_path}
1631154895.811858 cmd_parse_build_commands: 0 split-window
1631154895.811859 cmd_parse_build_commands: argv[0]=split-window
1631154895.811860 cmd_parse_build_commands: argv[1]=-c
1631154895.811861 cmd_parse_build_commands: argv[2]=#{pane_current_path}
1631154895.811863 cmd_parse_build_commands: argv[3]=-h
1631154895.811864 cmd_parse_build_commands: argv[4]=htop
1631154895.811869 cmd_parse: split-window: argv[0]=split-window
1631154895.811870 cmd_parse: split-window: argv[1]=-c
1631154895.811871 cmd_parse: split-window: argv[2]=#{pane_current_path}
1631154895.811873 cmd_parse: split-window: argv[3]=-h
1631154895.811874 cmd_parse: split-window: argv[4]=htop
1631154895.811879 cmd_parse_build_commands: split-window -h -c "#{pane_current_path}" htop
```

**Comment by nicm** [comment]
Hmm I'll take a look, I fixed a problem woth copying arguments, maybe that broke this..

**Comment by nicm** [comment]
I am not sure how this worked before since it was adding the commands to the wrong list...

I have applied this fix, please let me know if you see anything strange: [aa.diff.txt](https://github.com/tmux/tmux/files/7134194/aa.diff.txt)

**Comment by systemmonkey42** [comment]
> I am not sure how this worked before since it was adding the commands to the wrong list...

Ok, weird.  I wondered how it knew to add the options to the start and the command to the end.   might have been coincidence...

I'll give the patch a quick test.

**Comment by systemmonkey42** [comment]
This looks good so far, my "htop" example works
```
1631171320.117585 cmd_unpack_argv: argv[0]=csplit-window
1631171320.117587 cmd_unpack_argv: argv[1]=-h
1631171320.117588 cmd_unpack_argv: argv[2]=htop
1631171320.117590 cmd_parse_build_commands 0:0: csplit-window
1631171320.117591 cmd_parse_build_commands 0:1: -h
1631171320.117593 cmd_parse_build_commands 0:2: htop
1631171320.117596 cmd_parse_expand_alias: 0 alias csplit-window = split-window -c "#{pane_current_path}"
1631171320.117604 cmd_parse_expand_alias 0:0: split-window
1631171320.117605 cmd_parse_expand_alias 0:1: -c
1631171320.117606 cmd_parse_expand_alias 0:2: #{pane_current_path}
1631171320.117607 cmd_parse_expand_alias 0:3: -h
1631171320.117609 cmd_parse_expand_alias 0:4: htop
1631171320.117610 cmd_parse_build_commands 0:0: split-window
1631171320.117611 cmd_parse_build_commands 0:1: -c
1631171320.117612 cmd_parse_build_commands 0:2: #{pane_current_path}
1631171320.117613 cmd_parse_build_commands 0:3: -h
1631171320.117614 cmd_parse_build_commands 0:4: htop
1631171320.117621 args_parse: -c = #{pane_current_path}
1631171320.117622 args_parse: -h
1631171320.117624 args_parse: flags end at 4 of 5
1631171320.117625 args_parse: 4 = htop (type 1)
1631171320.117630 cmd_parse_build_commands: split-window -h -c "#{pane_current_path}" htop
1631171320.117633 cmd_parse_build_commands: split-window -h -c "#{pane_current_path}" htop
```
But the command that actually failed still fails.  I'll do more testing and let you know.

**Comment by systemmonkey42** [comment]
The second failure is technically unrelated...  it was just hidden by the first.

```
$ tmux run-shell -C 'display-message -p pane=#{pane_id}'
syntax error
$ tmux run-shell 'tmux display-message -p pane=#{pane_id}'
pane=%0
```

The formatting in `run-shell -C` is tripping up

```
1631172757.400339 args_make_commands_prepare: display-message -p pane=#{pane_id}
1631172757.400341 args_make_commands: display-message -p pane=#{pane_id}
1631172757.400344 yylex_token: display-message
1631172757.400345 yylex_token: -p
1631172757.400349 yylex_token: pane=#{pane_id
1631172757.400352 cmdq_error: syntax error
```

**Comment by nicm** [comment]
Hmm `run-shell` should still be expanding the `#{}` since you are using quotes. If you were using `{}` you would need to quote the `display-message` argument because `run-shell` wouldn't expand it. I'll take a look.

**Comment by nicm** [comment]
Oh maybe I accidentally removed expansion of string command arguments when I broke the code out...

**Comment by nicm** [comment]
Yes, I did and then I fixed it for commands that call `args_make_commands` (added an `expand` argument) but not for commands that call `args_make_commands_now`.

**Comment by nicm** [comment]
Try this please: [bb.diff.txt](https://github.com/tmux/tmux/files/7135262/bb.diff.txt)

**Comment by systemmonkey42** [comment]
Was that a standalone patch or should I have included the previous aa.diff?

The results were, um  confusing.
```
1631188720.299515 cmdq_fire_command </dev/pts/3>: (3349) run-shell -C "csplit-window -h vi #{pane_id}"
1631188720.299517 cmd_find_from_client: s=$0 0
1631188720.299518 cmd_find_from_client: wl=1 1 w=@0 bash
1631188720.299519 cmd_find_from_client: wp=%0
1631188720.299521 cmd_find_from_client: idx=none
1631188720.299523 cmd_find_target: target none, type pane, item 0x555ccbdbfce0, flags QUIET,CANFAIL
1631188720.299525 cmd_find_target: current is from queue
1631188720.299526 cmd_find_target: s=$0 0
1631188720.299527 cmd_find_target: wl=1 1 w=@0 bash
1631188720.299529 cmd_find_target: wp=%0
1631188720.299530 cmd_find_target: idx=none
1631188720.299532 args_make_commands_prepare: csplit-window -h vi #{pane_id}
1631188720.299533 args_make_commands: csplit-window -h vi #{pane_id}
1631188720.299536 yylex_token: csplit-window
1631188720.299537 yylex_token: -h
1631188720.299539 yylex_token: vi
1631188720.299541 cmd_parse_build_commands 0:0: csplit-window
1631188720.299543 cmd_parse_build_commands 0:1: -h
1631188720.299544 cmd_parse_build_commands 0:2: vi
1631188720.299547 cmd_parse_expand_alias: 0 alias csplit-window = split-window -c "#{pane_current_path}"
1631188720.299549 yylex_token: split-window
1631188720.299550 yylex_token: -c
1631188720.299552 yylex_token: #{pane_current_path}
1631188720.299554 cmd_parse_expand_alias 0:0: split-window
1631188720.299555 cmd_parse_expand_alias 0:1: -h
1631188720.299556 cmd_parse_expand_alias 0:2: vi
1631188720.299557 cmd_parse_expand_alias 0:3: -c
1631188720.299559 cmd_parse_expand_alias 0:4: #{pane_current_path}
1631188720.299560 cmd_parse_build_commands 0:0: split-window
1631188720.299561 cmd_parse_build_commands 0:1: -h
1631188720.299562 cmd_parse_build_commands 0:2: vi
1631188720.299564 cmd_parse_build_commands 0:3: -c
1631188720.299565 cmd_parse_build_commands 0:4: #{pane_current_path}
1631188720.299571 args_parse: -h
1631188720.299573 args_parse: flags end at 2 of 5
1631188720.299574 args_parse: 2 = vi (type 1)
1631188720.299575 args_parse: 3 = -c (type 1)
1631188720.299577 args_parse: 4 = #{pane_current_path} (type 1)
1631188720.299582 cmd_parse_build_commands: split-window -h vi -c "#{pane_current_path}"
```
```
csplit-window = split-window -c "#{pane_current_path}"

csplit-window -h vi #{pane_id} 
```
 was transformed into
```
split-window -h vi -c "#{pane_current_path}"
```
no sigh of #{pane_id}..

**Comment by systemmonkey42** [comment]
With both patch sets, it works perfectly.

```
1631189285.224944 message: /dev/pts/3 key /: split-window -h -c "#{pane_current_path}" vi "%0"
1631189285.224948 cmdq_fire_command </dev/pts/3>: (3713) split-window -h -c "#{pane_current_path}" vi "%0"
1631189285.224949 cmd_find_from_client: s=$0 0
1631189285.224951 cmd_find_from_client: wl=1 1 w=@0 bash
1631189285.224952 cmd_find_from_client: wp=%0
1631189285.224953 cmd_find_from_client: idx=none
1631189285.224955 cmd_find_target: target none, type pane, item 0x5562e20b1d30, flags NONE
1631189285.224957 cmd_find_target: current is from queue
1631189285.224958 cmd_find_target: s=$0 0
1631189285.224959 cmd_find_target: wl=1 1 w=@0 bash
1631189285.224960 cmd_find_target: wp=%0
1631189285.224961 cmd_find_target: idx=none
1631189285.224963 window_push_zoom: @0 0
1631189285.224966 spawn_pane: [split-window/0x5562e20b1d30], flags=0
1631189285.224967 spawn_pane: s=$0 wl=1 wp0=%0 idx=-1
1631189285.224969 spawn_pane: name=none
1631189285.224970 format_defaults: c=/dev/pts/3
1631189285.224971 format_defaults: s=$0
1631189285.224973 format_defaults: wl=none
1631189285.224974 format_defaults: wp=none
1631189285.224975 format_expand1: expanding format: #{pane_current_path}
1631189285.224977 format_expand1: found #{}: pane_current_path
1631189285.225004 format_replace: format 'pane_current_path' found: /tmp
1631189285.225007 format_replace: replaced 'pane_current_path' with '/tmp'
1631189285.225009 format_expand1: result is: /tmp
1631189285.225014 unref client 0x5562e211b4a0 (3 references)
1631189285.225021 window_add_pane: @0 after %1
1631189285.225024 window_pane_resize: %0 resize 78x51
1631189285.225026 screen_resize_cursor: new size 78x51, now 157x51 (cursor 26,1 = 26,1)
1631189285.225028 screen_reflow: cursor 26,1 is 4294967295,1
1631189285.225034 screen_reflow: new cursor is 26,1
1631189285.225035 screen_resize_cursor: cursor finished at 26,1 = 26,1
1631189285.225037 window_pane_resize: %1 resize 78x51
1631189285.225039 screen_resize_cursor: new size 78x51, now 157x51 (cursor 0,0 = 0,0)
1631189285.225040 screen_reflow: cursor 0,0 is 4294967295,0
1631189285.225046 screen_reflow: new cursor is 0,0
1631189285.225047 screen_resize_cursor: cursor finished at 0,0 = 0,0
1631189285.225115 spawn_pane: shell=/bin/bash
1631189285.225117 cmd_stringify_argv: 0 vi = vi
1631189285.225119 cmd_stringify_argv: 1 %0 = "%0"
1631189285.225121 spawn_pane: cmd=vi "%0"
1631189285.225122 spawn_pane: cwd=/tmp
1631189285.225123 spawn_pane: argv[0]=vi
1631189285.225124 spawn_pane: argv[1]=%0
1631189285.225126 spawn_pane: environment ARIA2C_HOST=http://localhost:6800
```

Thanks

**Comment by nicm** [comment]
You need both or you need to be at master + the second.

**Comment by nicm** [comment]
Applied now, thanks!
