### ISSUE TITLE
Sixel draws fails on certain height/width ratio

### ISSUE THREAD

**Issue by amigthea** [tmux/tmux#4739]
### Issue description

When I try to use [chafa](https://github.com/hpjansson/chafa), sometimes the drawing fails (o it's cleaned too early) and I noticed that's correlated to the panel dimension

here's an example video that shows what happens

https://github.com/user-attachments/assets/cb1a2597-ce05-47c5-b920-6957f082c774

cat.jpg dimension: 1920x1080
failed panel dimension: 215x36

### Required information

* tmux version (`tmux -V`).
**tmux 3.6**
* Platform (`uname -sp`).
**Arch Linux 6.17.9-arch1-1**
* Terminal in use (xterm, rxvt, etc).
**foot**
* $TERM *inside* tmux (`echo $TERM`).
**screen-256color**
* $TERM *outside* tmux (`echo $TERM`).
**foot**
* Logs from tmux (`tmux kill-server; tmux -vv new`).
**ND**

**Comment by amigthea** [comment]
@nicm I was able to reproduce this on the [default](https://github.com/tmux/tmux/blob/master/example_tmux.conf) configuration too and logged the session up after chafa command execution fails
[tmux-client.log](https://0x0.st/KtGL.txt)
[tmux-out.log](https://0x0.st/KtGV.txt)
[tmux-server.log](https://0x0.st/KtGW.txt)

**Comment by nicm** [comment]
Your image is too big for the  default buffer size of 1048576. Try increasing the `input-buffer-size` option.

**Comment by amigthea** [comment]
thank you for the suggestion but I already had it at 10485760, changing to 104857600 didn't solve this
edit: I recall that the first months of 2025 this same setup was working on master git of that time

**Comment by nicm** [comment]
The `input-buffer-size` is not changed in your log.

**Comment by amigthea** [comment]
I increased the `input-buffer-size` in the default configuration too, [here](https://0x0.st/Kw3C.txt)'s the logs until after the chafa command

**Comment by nicm** [comment]
OK, I see this - you have this image [in.sixel.txt](https://github.com/user-attachments/files/24030985/in.sixel.txt) and when the pane is too small for it, it doesn't draw.

tmux is sending an image but the image is invalid in some way, so clearly there is a problem with cropping.

When the pane is only a little bit too small, I get part of the image, but looks like it is cropped incorrectly (at the bottom rather than the top).

**Comment by amigthea** [comment]
I thought it could have been something like the encoding of the specific image but it happened with every image file I tried too (at that window/panel dimension)

**Comment by nicm** [comment]
This fixes it for me:
~~~~
diff --git a/image-sixel.c b/image-sixel.c
index 1c93d7a7..6d18a978 100644
--- a/image-sixel.c
+++ b/image-sixel.c
@@ -595,7 +595,7 @@ sixel_print(struct sixel_image *si, struct sixel_image *map, size_t *size)
        tmplen = xsnprintf(tmp, sizeof tmp, "\033P0;%uq", si->p2);
        sixel_print_add(&buf, &len, &used, tmp, tmplen);

-       if (si->set_ra) {
+       if (0 && si->set_ra) {
                tmplen = xsnprintf(tmp, sizeof tmp, "\"1;1;%u;%u", si->ra_x,
                    si->ra_y);
                sixel_print_add(&buf, &len, &used, tmp, tmplen);
~~~~
The original image has 1;1;1184;0 as the RA and it is the same in the cropped image, but that seems wrong, the new image should be smaller...

This was added in 7a78cdf78c00370d4ff1eb2c7cb5678412de9002... @bptato do you know what the problem is here?

**Comment by nicm** [comment]
Even with this commented out there is still something funny, because the first time I cat the image it appears then is immediately cleared, but the second time it works. I think this is a separate issue, maybe something to do with redraw or scrolling...

I have a 158x42 terminal and I split it once so the top pane is 158x11. These are the images with and without the change above:  [bad2.sixel.txt](https://github.com/user-attachments/files/24031338/bad2.sixel.txt) [good2.sixel.txt](https://github.com/user-attachments/files/24031336/good2.sixel.txt)

**Comment by bptato** [comment]
> The original image has 1;1;1184;0 as the RA and it is the same in the cropped image, but that seems wrong, the new image should be smaller...

In Kw3C.txt/in.sixel.txt I see `1;1;1184;665`.  If it turns into `1;1;1184;0` as in bad2.sixel.txt, then somehow the height is disappearing - that's certainly a bug, but I cannot reproduce it.  What cell size does this happen with? (`printf '\033[16t';read`)

(The other issue might be related to overprinting.  With 10x20 cells on a 191x34 pane:

```
#!/bin/sh
cat in.sixel.txt
sleep 1
printf a
sleep 1
```

The cursor lands on the last line of the cat (as opposed to the next line).  `printf a` then erases the poor thing from existence (same thing happens with shell prompt).
On other pane heights, I get a cursor on the next line.  But I'm not sure if this is the right behavior, because xterm outside tmux always puts the cursor on the last line.)

**Comment by nicm** [comment]
Here is my log from `cat ~/in.sixel.txt` with two panes, the upper one too small vertically for the image: [tmux-server-2659093.log](https://github.com/user-attachments/files/24033939/tmux-server-2659093.log)

Outside tmux:
~~~~
$ printf '\033[16t';read
^[[6;27;12t
~~~~
And inside:
~~~~
$ printf '\033[16t';read
^[[6;27;12t
$ tmux display -a|grep cell
client_cell_height=27
client_cell_width=12
window_cell_height=27
window_cell_width=12

**Comment by nicm** [comment]
In the RA in the output images, the height is zero, which I guess is the issue (sorry I misread it before and thought it was unchanged).

**Comment by bptato** [comment]
It seems I misunderstood the coordinate system.  Currently we do:

ra_y = max(min(ra_y, psy) - poy, 0)

which would have been fine if psy and poy were actually a slice as per my comment, but they aren't, poy is an offset into the image and psy is the desired size.  Swapping the operations should fix the 0-height bug:

```diff
diff --git a/image-sixel.c b/image-sixel.c
index 1c93d7a7..5c800461 100644
--- a/image-sixel.c
+++ b/image-sixel.c
@@ -455,12 +455,12 @@ sixel_scale(struct sixel_image *si, u_int xpixel, u_int ypixel, u_int ox,
 	new->p2 = si->p2;
 
 	new->set_ra = si->set_ra;
-	/* clamp to slice end */
-	new->ra_x = si->ra_x < psx ? si->ra_x : psx;
-	new->ra_y = si->ra_y < psy ? si->ra_y : psy;
-	/* subtract slice origin */
+	/* subtract offset */
 	new->ra_x = new->ra_x > pox ? new->ra_x - pox : 0;
 	new->ra_y = new->ra_y > poy ? new->ra_y - poy : 0;
+	/* clamp to size */
+	new->ra_x = si->ra_x < psx ? si->ra_x : psx;
+	new->ra_y = si->ra_y < psy ? si->ra_y : psy;
 	/* resize */
 	new->ra_x = new->ra_x * xpixel / si->xpixel;
 	new->ra_y = new->ra_y * ypixel / si->ypixel;
```

**Comment by nicm** [comment]
OK with this the image is valid, and if I `cat in.sixel.txt` it works, but it does not display the first time for some reason, weirdly...

**Comment by nicm** [comment]
I've applied this fix now, since it seems to be right, thanks! I don't know if there is another problem or if it is my terminal...

@amigthea do you still see the problem if you build from `master`?

**Comment by amigthea** [comment]
I tried to compile the master branch with [this PKGBUILD](https://0x0.st/Kwkt.txt) and install it but it I still get the same behaviour, I'm doing something wrong?

**Comment by nicm** [comment]
What does `tmux -V` show?

**Comment by nicm** [comment]
That file says 3.6a not master?

**Comment by amigthea** [comment]
> What does `tmux -V` show?

tmux next-3.7

> That file says 3.6a not master?

that's because I just edited the `source` and `sha256sums`, for testing purpose

**Comment by nicm** [comment]
OK can you show me the server log of the problem from using `master` (you may be hitting a different issue)?

Make sure you have `master` with `2e5e9c02982776a35a0378206966991e5dd4c723` (check `git log`).

**Comment by amigthea** [comment]
`git log`

<img width="746" height="128" alt="Image" src="https://github.com/user-attachments/assets/c013d200-24bd-4623-8deb-ad2bc50b8fca" />

and [here](https://0x0.st/KkIu.txt)'s the logs

**Comment by nicm** [comment]
I don't see the image being sent at all in this log?

**Comment by amigthea** [comment]
sorry I messed up the log collection, [here](https://0x0.st/KdBt.txt) is the one with the image

**Comment by nicm** [comment]
OK so the original bug looks fixed, your log has the right size in the output image:
~~~~
\033P0;1q"1;1;1184;665
~~~~
And if I take the image out and print it, it works. Let me see if I can see what is going on...

**Comment by amigthea** [comment]
maybe this visual behaviour can help you pinpoint the problematic part of code, the other panel seems to redraw incorrectly the split panel line after each execution

https://github.com/user-attachments/assets/0d490d7f-28f0-4351-8397-3b8e7baeb5ec

**Comment by nicm** [comment]
OK I think this is the same thing I am seeing, which is not really a bug - when the image is drawn and this causes the pane to scroll, the cursor is left on the last line of the image which causes the shell to immediately write over it with the prompt. tmux does not support writing text over images, so the image is removed.

If you add `; cat` or `; read` to the end of your command, does it fix the problem?

**Comment by amigthea** [comment]
executing `chafa ./cat.jpg; read` waits for input like this

<img width="1303" height="895" alt="Image" src="https://github.com/user-attachments/assets/c70b0c09-71b2-4e17-87ce-f8e9fee12465" />

**Comment by nicm** [comment]
OK, so it seems like it is working as expected now. Adding `; echo` instead of `; read` would work because it would scroll again and put the prompt after the image.

**Comment by amigthea** [comment]
yes, I confirm you that also with `; echo` the image is displayed correctly (altough the split line scroll behaviour remains)

**Comment by nicm** [comment]
I don't see the extra line, do you see it if you `cat` the image file https://github.com/user-attachments/files/24030985/in.sixel.txt as well or only if you run chafa?

**Comment by amigthea** [comment]
I'm seeing this behaviours (both tested on a fresh terminal session)

with `cat in.sixel.txt`
- the first execution do not keep the drawn image and print the extra line
- from second execution and on it correctly keeps the drawn image and do not add more extra line (but the double line from first execution remains)

<img width="1216" height="805" alt="Image" src="https://github.com/user-attachments/assets/32f3f6a4-45e6-4460-a844-e289e527eb0c" />

with `chafa` it keeps [this](https://github.com/tmux/tmux/issues/4739#issuecomment-3631035286) behaviour

**Comment by nicm** [comment]
I see the way the image displays on the second attempt without `echo`, and it works if the terminal is not split, so clearly we are doing something inconsistent...

**Comment by amigthea** [comment]
on a `215x72` no split pane I confirm that the first execution is effective, but if I reduce the terminal emulator window so that the pane is `215x36` (like if it was splitted), `cat in.sixel.txt` seems to converge to the same `chafa` behaviour

**Comment by nicm** [comment]
Yes, for me, if you are on the second line it is wrong, but on the first or third line it is OK:
~~~~
clear;echo;cat ~/in.sixel.txt # wrong
clear;cat ~/in.sixel.txt # OK
clear;echo;echo;cat ~/in.sixel.txt # OK
~~~~
But the funny thing is, the "wrong" behaviour is really sort of the *right* behaviour, because if you try the same outside tmux, you will see the prompt is left on the last line of the image, and overwrites it.

Removing the image straight away is not ideal, so it would really be better if we always just added an extra line...

**Comment by nicm** [comment]
This fixes it for me - we were only scrolling up if the image was greater than the screen size, not if it was exactly the same:
~~~~
--- a/screen-write.c
+++ b/screen-write.c
@@ -2339,7 +2339,7 @@ screen_write_sixelimage(struct screen_write_ctx *ctx, struct sixel_image *si,
        }

        sy = screen_size_y(s) - cy;
-       if (sy < y) {
+       if (sy <= y) {
                lines = y - sy + 1;
                if (image_scroll_up(s, lines) && ctx->wp != NULL)
                        ctx->wp->flags |= PANE_REDRAW;

**Comment by amigthea** [comment]
for me that diff makes `cat in.sixel.txt` works on first execution on a splitted `215x35` pane, but if I resize the terminal emulator window, and get the a single pane of `215x36`, both `cat in.sixel.txt` and `chafa` fails

**Comment by nicm** [comment]
It works for me with any size of window, can you show the log of the failure?

**Comment by amigthea** [comment]
probably I messed up somewhere during the compilation, [here](https://0x0.st/KF0t.txt)'s the log

**Comment by nicm** [comment]
Are you sure you have build from master with this change? Can you show me a video of what is happening now?

I can't see anything obvious in the log and I can't make it behave incorrectly...

**Comment by amigthea** [comment]
I cloned the master git locally, edited `screen-write.c` as suggested and built from that; can you push that change to the repo so we can exclude problem with my manual edit? sorry for my annoying skill
ps: the behaviour is the same of the previous videos (flash image and double lines)

**Comment by amigthea** [comment]
I've made some progress in pinpointing the problem. Seems to be related to certain combination of terminal emulator font dimension/line height and tmux panel size . here some test with different font dimension at a fixed tmux panel height

`font=monospace:size=8` # foot default
`font=monospace:size=8.5`
`font=monospace:size=9`
`font=monospace:size=10`
`font=monospace:size=11`
`font=monospace:size=11.5`
`font=monospace:size=12`
`font=monospace:size=12.5`
`font=monospace:size=13`
`font=monospace:size=14.5`

**image is not printed and tmux window has bottom padding**
<img width="192" height="69" alt="Image" src="https://github.com/user-attachments/assets/d4415f1a-6a3d-4ffe-af52-43a3684c10fc" />


`font=monospace:size=9.5`
`font=monospace:size=13.5`
`font=monospace:size=14`

**image is printed and tmux window has bottom padding**
<img width="124" height="68" alt="Image" src="https://github.com/user-attachments/assets/096094e7-f237-4537-94bb-bc6c9ef117c6" />

`font=monospace:size=10.5`

**image is printed and tmux window does not have bottom padding**
<img width="186" height="93" alt="Image" src="https://github.com/user-attachments/assets/96fd8c28-e2ce-49dd-8695-2c6a8a446e77" />

this considering the default horizontal split dimension, because if I move the split line up or down, the results starts to differ and mix. Is this what the `screen-write.c` fix is about? or is not related?

**Comment by nicm** [comment]
OK, I have applied this change since it fixes it for me, and I have also added some extra logging to image output.

Could you please rebuild tmux from latest master and then show the bug by doing the same thing with a working and a nonworking font size and send me the two server logs?

**Comment by amigthea** [comment]
built from master and tested with standard horizontal pane split, where image is correctly rendered with a `10.5` font size, and with a resized (increased by one step) horizontal pane split with the same `10.5` font size

[working size logs](https://0x0.st/Prhj.txt)
[bugged size logs](https://0x0.st/Prhe.txt)

**Comment by nicm** [comment]
Thanks, I think I have reproduced it, the size of the image is now one line too big when it fills the pane. Try this please: 

[sixel.diff.txt](https://github.com/user-attachments/files/24235373/sixel.diff.txt)

**Comment by amigthea** [comment]
that seems to fix it definitely, cannot thank you enough for your time ♥️

**Comment by nicm** [comment]
Great, I have applied this now, let me know if you see any other problems. Thanks!
